language: python
python:
  - '3.6'

install:
  - pip install -r requirements.txt

script:
  - py.test amos-latest-forecast-copy
  - py.test amos-latest-forecast-rename

before_deploy:
  - pip install awscli

deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master
